language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="Adafruit IO Arduino Library"


before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
    - arduino --install-library "Adafruit IO Arduino","Adafruit MQTT Library","ArduinoHttpClient","Adafruit Unified Sensor","Adafruit NeoPixel","DHT sensor library", "Adafruit BME280 Library", "Adafruit SGP30 Sensor", "Adafruit ADT7410 Library"

script:
    # build ESP8266 target
    - build_platform esp8266
    # build SAMD target
    - arduino --install-library "WiFi101"
    - build_platform zero
